//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyclops.MainApplication.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Conference {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Conference() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cyclops.MainApplication.Localization.Conference", typeof(Conference).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already banned in this conference..
        /// </summary>
        public static string AlreadyBannedMessage {
            get {
                return ResourceManager.GetString("AlreadyBannedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are banned due the reason: &apos;{0}&apos;..
        /// </summary>
        public static string BanMessage {
            get {
                return ResourceManager.GetString("BanMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prove you are not a bot:.
        /// </summary>
        public static string CaptchaMessage {
            get {
                return ResourceManager.GetString("CaptchaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} {1}.
        /// </summary>
        public static string ChangeRole {
            get {
                return ResourceManager.GetString("ChangeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing subject.
        /// </summary>
        public static string ChangeSubject {
            get {
                return ResourceManager.GetString("ChangeSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has changed subject to: {1}.
        /// </summary>
        public static string ChangeSubjectByParticipant {
            get {
                return ResourceManager.GetString("ChangeSubjectByParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to change subject..
        /// </summary>
        public static string ChangeSubjectError {
            get {
                return ResourceManager.GetString("ChangeSubjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clears the output are.
        /// </summary>
        public static string ClearTip {
            get {
                return ResourceManager.GetString("ClearTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy (Ctrl+C).
        /// </summary>
        public static string CopyText {
            get {
                return ResourceManager.GetString("CopyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick:.
        /// </summary>
        public static string CurrentUserNick {
            get {
                return ResourceManager.GetString("CurrentUserNick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string CurrentUserStatus {
            get {
                return ResourceManager.GetString("CurrentUserStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status text:.
        /// </summary>
        public static string CurrentUserStatusText {
            get {
                return ResourceManager.GetString("CurrentUserStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables all sounds.
        /// </summary>
        public static string DisableSoundsTip {
            get {
                return ResourceManager.GetString("DisableSoundsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect due &apos;{0}&apos;..
        /// </summary>
        public static string DisconnectMessage {
            get {
                return ResourceManager.GetString("DisconnectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit subject.
        /// </summary>
        public static string EditSubjectTooltip {
            get {
                return ResourceManager.GetString("EditSubjectTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string EditVcard {
            get {
                return ResourceManager.GetString("EditVcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered..
        /// </summary>
        public static string EnteredToTheRoom {
            get {
                return ResourceManager.GetString("EnteredToTheRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entering....
        /// </summary>
        public static string Entering {
            get {
                return ResourceManager.GetString("Entering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find text.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy link.
        /// </summary>
        public static string HyperlinkMenuCopy {
            get {
                return ResourceManager.GetString("HyperlinkMenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string HyperlinkMenuOpen {
            get {
                return ResourceManager.GetString("HyperlinkMenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in ie.
        /// </summary>
        public static string HyperlinkMenuOpenInIe {
            get {
                return ResourceManager.GetString("HyperlinkMenuOpenInIe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code..
        /// </summary>
        public static string InvalidCaptchaCode {
            get {
                return ResourceManager.GetString("InvalidCaptchaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password..
        /// </summary>
        public static string InvalidPasswordErrorMessage {
            get {
                return ResourceManager.GetString("InvalidPasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is now known as {1}..
        /// </summary>
        public static string IsNowKnownAs {
            get {
                return ResourceManager.GetString("IsNowKnownAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are kicked due the reason: &apos;{0}&apos;..
        /// </summary>
        public static string KickMessage {
            get {
                return ResourceManager.GetString("KickMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me.
        /// </summary>
        public static string Me {
            get {
                return ResourceManager.GetString("Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action you tried to perform is not allowed at this conference..
        /// </summary>
        public static string MethodNotAllowedError {
            get {
                return ResourceManager.GetString("MethodNotAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New nick in ({0}).
        /// </summary>
        public static string NewNick {
            get {
                return ResourceManager.GetString("NewNick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New nick and status.
        /// </summary>
        public static string NewNickDialogCaption {
            get {
                return ResourceManager.GetString("NewNickDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick conflict. Please, rejoin with another one..
        /// </summary>
        public static string NickConflictMessage {
            get {
                return ResourceManager.GetString("NickConflictMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference is not found..
        /// </summary>
        public static string NotFoundError {
            get {
                return ResourceManager.GetString("NotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only members can join to this conference..
        /// </summary>
        public static string OnlyMembersAccess {
            get {
                return ResourceManager.GetString("OnlyMembersAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect in {0} seconds....
        /// </summary>
        public static string ReconnectStart {
            get {
                return ResourceManager.GetString("ReconnectStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is now administrator.
        /// </summary>
        public static string RoleAdmin {
            get {
                return ResourceManager.GetString("RoleAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was banned.
        /// </summary>
        public static string RoleBanned {
            get {
                return ResourceManager.GetString("RoleBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was devoiced.
        /// </summary>
        public static string RoleDevoiced {
            get {
                return ResourceManager.GetString("RoleDevoiced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was kicked.
        /// </summary>
        public static string RoleKicked {
            get {
                return ResourceManager.GetString("RoleKicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is now member.
        /// </summary>
        public static string RoleMember {
            get {
                return ResourceManager.GetString("RoleMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is now moderator.
        /// </summary>
        public static string RoleModer {
            get {
                return ResourceManager.GetString("RoleModer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is now owner.
        /// </summary>
        public static string RoleOwner {
            get {
                return ResourceManager.GetString("RoleOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is now regular user.
        /// </summary>
        public static string RoleRegular {
            get {
                return ResourceManager.GetString("RoleRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This conference has password (inputbox is not implemented yet :().
        /// </summary>
        public static string RoomHasPassword {
            get {
                return ResourceManager.GetString("RoomHasPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all (Ctrl+A).
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send private message.
        /// </summary>
        public static string SendPrivateMessage {
            get {
                return ResourceManager.GetString("SendPrivateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send public message.
        /// </summary>
        public static string SendPublicMessage {
            get {
                return ResourceManager.GetString("SendPublicMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service unavailable..
        /// </summary>
        public static string ServiceUnavailableError {
            get {
                return ResourceManager.GetString("ServiceUnavailableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows settings view.
        /// </summary>
        public static string SettingsTip {
            get {
                return ResourceManager.GetString("SettingsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows smiles&apos; selection dialog.
        /// </summary>
        public static string SmilesTip {
            get {
                return ResourceManager.GetString("SmilesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has changed his status to &quot;{1}&quot; - &quot;{2}&quot;.
        /// </summary>
        public static string StatusChangingFormat {
            get {
                return ResourceManager.GetString("StatusChangingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has joined to us..
        /// </summary>
        public static string UserJoinMessage {
            get {
                return ResourceManager.GetString("UserJoinMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has left the conference..
        /// </summary>
        public static string UserLeaveMessage {
            get {
                return ResourceManager.GetString("UserLeaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View details.
        /// </summary>
        public static string ViewVcard {
            get {
                return ResourceManager.GetString("ViewVcard", resourceCulture);
            }
        }
    }
}
