//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyclops.MainApplication.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Settings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Settings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cyclops.MainApplication.Localization.Settings", typeof(Settings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set &apos;away&apos; status on idle, in minutes:.
        /// </summary>
        public static string AutoAway {
            get {
                return ResourceManager.GetString("AutoAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set &apos;N/A&apos; status on idle, in minutes:.
        /// </summary>
        public static string AutoExtendedAway {
            get {
                return ResourceManager.GetString("AutoExtendedAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blinking only on privates (ignore public chats):.
        /// </summary>
        public static string BlinkOnlyOnPrivates {
            get {
                return ResourceManager.GetString("BlinkOnlyOnPrivates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string CommonGroup {
            get {
                return ResourceManager.GetString("CommonGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string CommonHeader {
            get {
                return ResourceManager.GetString("CommonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string ConnectionGroup {
            get {
                return ResourceManager.GetString("ConnectionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable all sounds:.
        /// </summary>
        public static string DisableAllSounds {
            get {
                return ResourceManager.GetString("DisableAllSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable blinking:.
        /// </summary>
        public static string DisableBlinking {
            get {
                return ResourceManager.GetString("DisableBlinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit connection configuration:.
        /// </summary>
        public static string EditConnectionConfiguration {
            get {
                return ResourceManager.GetString("EditConnectionConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable error pop-up notifications:.
        /// </summary>
        public static string EnableErrorsPopups {
            get {
                return ResourceManager.GetString("EnableErrorsPopups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable privates pop-up notifications:.
        /// </summary>
        public static string EnablePrivatesPopups {
            get {
                return ResourceManager.GetString("EnablePrivatesPopups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide on window closing (close an app otherwise):.
        /// </summary>
        public static string HideOnClosing {
            get {
                return ResourceManager.GetString("HideOnClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot-keys.
        /// </summary>
        public static string HotkeyHeader {
            get {
                return ResourceManager.GetString("HotkeyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface.
        /// </summary>
        public static string InterfaceHeader {
            get {
                return ResourceManager.GetString("InterfaceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string NotificationsGroup {
            get {
                return ResourceManager.GetString("NotificationsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pop-up showing time in sec.:.
        /// </summary>
        public static string PopupStaysOpenning {
            get {
                return ResourceManager.GetString("PopupStaysOpenning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show users&apos; entry and exits.
        /// </summary>
        public static string ShowEntryAndExits {
            get {
                return ResourceManager.GetString("ShowEntryAndExits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show roles&apos; changes.
        /// </summary>
        public static string ShowRoleChanges {
            get {
                return ResourceManager.GetString("ShowRoleChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show status changes in a chat:.
        /// </summary>
        public static string ShowStatusChanges {
            get {
                return ResourceManager.GetString("ShowStatusChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit smiles images in a message:.
        /// </summary>
        public static string SmileLimit {
            get {
                return ResourceManager.GetString("SmileLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play sounds event if chat is an active:.
        /// </summary>
        public static string SoundEvenIfActive {
            get {
                return ResourceManager.GetString("SoundEvenIfActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On incoming private:.
        /// </summary>
        public static string SoundOnIncomingPrivate {
            get {
                return ResourceManager.GetString("SoundOnIncomingPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On incoming public:.
        /// </summary>
        public static string SoundOnIncomingPublic {
            get {
                return ResourceManager.GetString("SoundOnIncomingPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has changed his status:.
        /// </summary>
        public static string SoundOnStatusChange {
            get {
                return ResourceManager.GetString("SoundOnStatusChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On system message:.
        /// </summary>
        public static string SoundOnSystemMessage {
            get {
                return ResourceManager.GetString("SoundOnSystemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has joined:.
        /// </summary>
        public static string SoundOnUserJoin {
            get {
                return ResourceManager.GetString("SoundOnUserJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has left:.
        /// </summary>
        public static string SoundOnUserLeave {
            get {
                return ResourceManager.GetString("SoundOnUserLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds.
        /// </summary>
        public static string SoundsHeader {
            get {
                return ResourceManager.GetString("SoundsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start chat on windows start up:.
        /// </summary>
        public static string StartWithWindows {
            get {
                return ResourceManager.GetString("StartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusHeader {
            get {
                return ResourceManager.GetString("StatusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        public static string StyleHeader {
            get {
                return ResourceManager.GetString("StyleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray.
        /// </summary>
        public static string TrayGroup {
            get {
                return ResourceManager.GetString("TrayGroup", resourceCulture);
            }
        }
    }
}
