//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyclops.MainApplication.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConferenceList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConferenceList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cyclops.MainApplication.Localization.ConferenceList", typeof(ConferenceList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already in this conference.
        /// </summary>
        public static string AlreadyInRoom {
            get {
                return ResourceManager.GetString("AlreadyInRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select item to get description.
        /// </summary>
        public static string DefaultConferenceDescInList {
            get {
                return ResourceManager.GetString("DefaultConferenceDescInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter:.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick:.
        /// </summary>
        public static string Nick {
            get {
                return ResourceManager.GetString("Nick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conferences.
        /// </summary>
        public static string RoomList {
            get {
                return ResourceManager.GetString("RoomList", resourceCulture);
            }
        }
    }
}
